#!/usr/bin/env bash
# vim: set filetype=bash : 
#
#
# This file is intended for exporting ENV variables...
#

export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
export EDITOR=/usr/bin/nvim

export_check "$ANDROID_SDK_ROOT/platform-tools/"
export_check "$HOME/.local/bin/"
