#!/usr/bin/env bash
# vim: set filetype=bash :

# this file is used for importing other files...

[[ -f ./bash_helpers ]] && . ./bash_helpers
[[ -f ./bash_imports ]] && . ./bash_imports
[[ -f ./bash_aliases ]] && . ./bash_aliases
[[ -f ./bash_ui ]] && . ./bash_ui
