#!/usr/bin/env bash
# vim: set filetype=bash :

# this file is used for importing other files...

[[ -f ~/.config/bash/bash_helpers ]] && . ~/.config/bash/bash_helpers
[[ -f ~/.config/bash/bash_imports ]] && . ~/.config/bash/bash_imports
[[ -f ~/.config/bash/bash_aliases ]] && . ~/.config/bash/bash_aliases
[[ -f ~/.config/bash/bash_ui ]] && . ~/.config/bash/bash_ui
[[ -f ~/.config/bash/zoxide ]] && . ~/.config/bash/zoxide
