#!/usr/bin/env bash
# vim: set filetype=bash :
# =============================================================================
#
# To initialize zoxide, add this to your configuration (usually ~/.bashrc):
#
eval "$(zoxide init bash)"
